FROM python:3-slim

RUN mkdir /myapp
WORKDIR /myapp
COPY source/myapp.py source/requirements.txt ./
RUN pip install -r requirements.txt

RUN addgroup --system app && adduser --system --group app
RUN apt-get update && apt-get upgrade

USER app

CMD ["python", "./myapp.py"]
